# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
    paths-ignore:
    - 'docs/**'    
  pull_request:
    branches: [ main ]
    paths-ignore:
    - 'docs/**'    

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Cache local Maven repository
      # https://github.com/actions/cache/blob/main/examples.md#java---maven
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-    
    - name: Cache zebrajs
      id: cache-zebrajs
      uses: actions/cache@v2
      with:
        path: zebrajs/target/generated/js/teavm/classes.js
        key: ${{ runner.os }}-jdk11-${{ hashFiles('pom.xml', 'zebrajs/**', 'zebra-teavm/**') }}                            
    - name: Set up JDK
      # https://github.com/actions/cache#Skipping-steps-based-on-cache-hit
      if: steps.cache-zebrajs.outputs.cache-hit != 'true'     
      uses: actions/setup-java@v1
      with:
        java-version: '14'
    - name: Build and test with Maven
      if: steps.cache-zebrajs.outputs.cache-hit != 'true'
      run: mvn -B package --file pom.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      

    - name: Cache node modules
      # https://github.com/actions/cache/blob/main/examples.md#node---npm
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    # https://docs.github.com/en/actions/guides/building-and-testing-nodejs
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: npm install and npm run build
      # https://coryrylan.com/blog/building-angular-cli-projects-with-github-actions
      run: |
        npm ci
        npm run build:ci
      working-directory: ./zebra-demo

